from datetime import datetime

from pydantic import BaseModel


class JobMatchRequest(BaseModel):
    cv_id: int
    job_id: int


class JobMatchResult(BaseModel):
    match_score: int  # 0-100
    matched_skills: list[str]
    missing_skills: list[str]
    suggested_improvements: list[str]
    summary: str


class CVTailoringRequest(BaseModel):
    cv_id: int
    job_id: int


class CVTailoringResult(BaseModel):
    summary_suggestions: list[str]
    experience_improvements: list[str]
    skills_suggestions: list[str]
    keywords_to_emphasize: list[str]
    disclaimer: str = (
        "These suggestions are based solely on the content of your CV. "
        "Do not add skills, experience, or qualifications you do not have."
    )


class CoverLetterRequest(BaseModel):
    cv_id: int
    job_id: int
    tone: str = "professional"


class CoverLetterResult(BaseModel):
    cover_letter: str
    disclaimer: str = (
        "This cover letter was generated by AI based on your CV and the job description. "
        "Review it carefully before use."
    )


class AIQuotaRead(BaseModel):
    used: int
    limit: int
    remaining: int
    resets_at: datetime


class AIAnalysisRead(BaseModel):
    model_config = {"from_attributes": True}

    id: int
    cv_id: int
    job_id: int
    analysis_type: str
    prompt_version: str
    result_json: dict
